FROM ubuntu:noble

SHELL ["/bin/bash", "-c"]

RUN apt update && apt install -y software-properties-common && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -y && apt update

RUN apt install unzip git curl wget php8.2-cli php8.2-bcmath php8.2-sqlite3 php8.2-intl php8.2-curl php8.2-gmp php8.2-mysql php8.2-redis php8.2-swoole php8.2-gd php8.2-imagick php8.2-intl php8.2-mbstring php8.2-xml php8.2-zip php8.2-xdebug -y

RUN echo 'swoole.use_shortname=Off' >> /etc/php/8.2/cli/conf.d/25-swoole.ini \
  && cat <<'EOF' > /etc/php/8.2/cli/conf.d/20-xdebug.ini
[xdebug]
zend_extension=xdebug.so
xdebug.client_host = localhost
xdebug.client_port = 9003
;xdebug.force_display_errors = 1
;xdebug.force_error_reporting = 1
xdebug.mode = debug
xdebug.show_error_trace = 1
xdebug.show_exception_trace = 1
;xdebug.show_local_vars = 1
xdebug.start_with_request = yes
EOF

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash

RUN \. "/root/.nvm/nvm.sh" && nvm install 22

RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === 'c8b085408188070d5f52bcfe4ecfbee5f727afa458b2573b8eaaf77b3419b0bf2768dc67c86944da1544f06fa544fd47') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

EXPOSE 9501 9502 9503
